---
- name: >
    Installs PHP, WP-CLI, MariaDB, WordPress, PHP-FPM, Nginx, Apache2, HHVM

  hosts: webservers
  remote_user: root

  roles:
    - common
    - php
    - wp-cli
    - mariadb
    - wordpress-install
    - php-fpm
    - nginx
    - apache
    - hhvm
    - redis
    - monit

