---
- name: WordPress on Nginx (no FastCGI caching), PHP-FPM, MariaDB

  hosts: wphv
  remote_user: root
  vars:
    wp_php_fpm: true
    fpm_start: true

  roles:
    - reset-all-configs
    - php-fpm
    - nginx

